# Generated by rust2rpm 28
%bcond check 1

# prevent library files from being installed
%global cargo_install_lib 0

%global crate bluetui

Name:           bluetui
Version:        0.8.0
Release:        %autorelease
Summary:        TUI for managing bluetooth on Linux

License:        GPL-3.0
URL:            https://crates.io/crates/bluetui
Source:         %{crates_source}
Source:         bluetui-0.8.0-vendor.tar.xz

BuildRequires:  cargo-rpm-macros >= 26

%global _description %{expand:
TUI for managing bluetooth on Linux.}

%description %{_description}

%package     -n %{crate}
Summary:        %{summary}
# FIXME: paste output of %%cargo_license_summary here
License:        GPL-3.0
# LICENSE.dependencies contains a full license breakdown

%description -n %{crate} %{_description}

%files       -n %{crate}
%license LICENSE
%license LICENSE.dependencies
%license cargo-vendor.txt
%doc Readme.md
%doc Release.md
%{_bindir}/bluetui

%prep
%autosetup -n %{crate}-%{version} -p1 -a1
%cargo_prep -v vendor

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies
%{cargo_vendor_manifest}

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog

